Psync
jpmedley/mdn-drafts pull request #4
Opened 2020-08-24 12:42 UTC by Rumyra

Honestly I'll probably go through this better when I add to MDN. There was a lot of copying and pasting with this one, it'll be easier to check flow in the editor I think

2020-08-27 17:51 UTC, jpmedley requested changes
You're getting material in the right place and it's easily readable. I found a few typos and made some suggestions.

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncEvent/PeriodicSyncEvent_PeriodicSyncEvent_Constructor.html
> +<p class="summary">The <strong><code>PeriodicSyncEvent()</code></strong> constructor creates a new {{domxref("PeriodicSyncEvent")}} object which creates a new {{domxref('PeriodicSyncEvent')}} object.
```suggestion
<p class="summary">The <strong><code>PeriodicSyncEvent()</code></strong> constructor creates a new {{domxref("PeriodicSyncEvent")}} object. This constructor is not typically used. The browser creates these objects itself and provides them to {{domxref('ServiceWorkerGlobalScope.onperiodicsync')}} callback.</p></p>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncEvent/PeriodicSyncEvent_PeriodicSyncEvent_Constructor.html
> +<p>This examples constructs a new {{domxref('PeriodicSyncEvent')}} with the relevant associated tag.</p>
```suggestion
<p>This example constructs a new {{domxref('PeriodicSyncEvent')}} with the relevant associated tag.</p>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncEvent/PeriodicSyncEvent_landing_landing.html
> +<p class="summary">The <code>PeriodicSyncEvent</code> interface of the <a href="https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_APIs">Web Periodic Background
```suggestion
<p class="summary">The <code>PeriodicSyncEvent</code> interface of the {{domxref('Web Periodic Background Synchronization API')}} provides a way to run tasks in the service worker with network connectivity. An instance of this event is passed to the {{domxref('ServiceWorkerGlobalScope.onperiodicsync')}} handler. This happens periodically, at an interval greater than or equal to that set in {{domxref('PeriodicSyncManager.register()')}}. Other browser-specific factors such as the user's engagement with the site decide the actual interval.</p>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncEvent/PeriodicSyncEvent_landing_landing.html
> +<p>In this section, describe the API's purpose and usage cases in a bit more detail — why was a need recognized for it? What problems does it solve? What concepts does it involve? How do you use it,
Did you intend to leave the boilerplate in this file?

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncEvent/PeriodicSyncEvent_landing_landing.html
> +<div>{{draft}}{{DefaultAPISidebar("Periodic Background Sync")}}</div>
Did my tool spit this out? This is the wrong boilerplate for an interface landing page. 

I should have mentioned this. I have no automated way to generate a boilerplate umbrella boilerplate landing/overview page for for a whole spec, so I have it spit one out for every interface and throw out all but one. The hierarchy of pages should look like this. (Though the overview and interface pages are at parallel URLs. I'm guessing that overview pages were an afterthought.) 

```
overview
  -interface
    -interface.member
    -interface.member
  -interface
    -interface.member
    -interface.member
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncEvent/PeriodicSyncEvent_tag_property.html
> +<p class="summary">The <strong><code>tag</code></strong> read-only property of the {{domxref("PeriodicSyncEvent")}} interface returns the developer-defined identifier for the {{domxref('PeriodicSyncE
Please mention somehow that this is the tag defined when calling `PeriodicSyncManager.register()`. Provide a link.

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncEvent/PeriodicSyncEvent_tag_property.html
> +<p>The following example listening for a periodic sync event in the service worker, and accessing the <code>tag</code> property.</p>
```suggestion
<p>The following example shows listening for a periodic sync event in the service worker, and accessing the <code>tag</code> property.</p>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_PeriodicSyncManager_interface.html
> +<p class="summary">The <strong><code>PeriodicSyncManager</code></strong> interface of the {{domxref('Web Periodic Background Synchronization')}} provides a way to register tasks to be run in a servic
```suggestion
<p class="summary">The <strong><code>PeriodicSyncManager</code></strong> interface of the {{domxref('Web Periodic Background Synchronization API')}} provides a way to register tasks to be run in a service worker at periodic intervals with network connectivity. These tasks are referred to as periodic background sync requests. Access <code>PeriodicSyncManager</code> through the {{domxref('ServiceWorkerRegistration.periodicSync')}}.</p>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_PeriodicSyncManager_interface.html
> +  <dt>{{domxref('PeriodicSyncManager. getTags')}}</dt>
```suggestion
  <dt>{{domxref('PeriodicSyncManager.getTags')}}</dt>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_PeriodicSyncManager_interface.html
> +  <dt>{{domxref('PeriodicSyncManager. unregister')}}</dt>
```suggestion
  <dt>{{domxref('PeriodicSyncManager.unregister')}}</dt>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_PeriodicSyncManager_interface.html
> +<h1>Removing a periodic sync to stop syncing articles in the background</h1>
```suggestion
<h1>Removing a Periodic Sync</h1>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_PeriodicSyncManager_interface.html
> +<h3>Checking if a periodic sync task with a given tag is registered</h3>
```suggestion
<h3>Verifying a Periodic Sync by tag</h3>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_PeriodicSyncManager_interface.html
> +<h3>Requesting a periodic sync</h3>
```suggestion
<h3>Requesting a Periodic Sync</h3>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_getTags_method.html
> +<p>A {{jsxref('Promise')}} which resolves with a list of {{jsxref('String')}} object representing tags that are currently registered for periodic syncing.</p>
```suggestion
<p>A {{jsxref('Promise')}} which resolves with a list of {{jsxref('String')}} objects representing tags that are currently registered for periodic syncing.</p>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +<p>The background sync api allows web applications to alert their service worker to make any updates, at a periodic time interval. Uses may include fetching latest content whilst a device is connecte
There's also a (non-periodic) [background sync API](https://wiki.developer.mozilla.org/en-US/docs/Web/API/SyncManager). Make sure you use '*periodic* background sync' in every case.

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +<p>The minimum time interval is set when the API is invoked, however the user agent might also take into account other factors which affect when the service worker receives the event. For instance pr
```suggestion
<p>The minimum time interval is set when the API is invoked; however the user agent might also take into account other factors which affect when the service worker receives the event. For instance previous website engagement, or connection to a known network.</p>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +<p>The {{domxref('PeriodicSyncManager')}} interface is available through the {{domxref('ServiceWorker.periodicSync','periodicSync')}} property of a service worker registration. A unique tag identifie
```suggestion
<p>The {{domxref('PeriodicSyncManager')}} interface is available through {{domxref('ServiceWorkerRegistration.periodicSync')}}. A unique tag identifier is set to 'name' the sync event, which can then be listened for within the {{domxref('ServiceWorker')}} script. Once the event is received you can then run any functionality available, such as updating caches or fetching new resources.</p>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +</div>
Is this because an installed PWA is a higher level of user engagement than merely having a service worker?

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +  You can check if a pwa has been installed using the get installed related apps api https://wicg.github.io/get-installed-related-apps/spec/ -->
Ask Pete LePage if there's a way to infer a PWA. The problem with getInstalledRelatedApps() is it's Chrome only and there's no enthusiasm for it from other browser vendors.

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +  <dd>Provides a way to register tasks to be run in a service worker at periodic intervals with network connectivity. These tasks are referred to as periodic background sync requests.</dd>
```suggestion
  <dd>Registers tasks to be run in a service worker at periodic intervals with network connectivity. These tasks are referred to as periodic background sync requests.</dd>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +  <dt>{{domxref('PeriodicSyncManager. PeriodicSyncEvent')}}</dt>
```suggestion
  <dt>{{domxref('PeriodicSyncManager.PeriodicSyncEvent')}}</dt>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +  <dd>Provides a way to run tasks in the service worker with network connectivity.</dd>
Wouldn't it be accurate to say this is the event passed to the callback when synchronization occurs? (Or something to that effect.)

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +<p>The following additions to the {{domxref('Service Worker API')}} have been specified in the Periodic Background Sync specification to provide an entry point for using periodic sync.</p>
Active voice, please.

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +  <dd>An event handler fired whenever a {{Event("periodicsync")}} event occurs. This happens at timed intervals, which can be specified when registering a {{domxref('PeriodicSyncManager')}}.</dd>
```suggestion
  <dd>An event handler fired whenever a {{Event("periodicsync")}} event occurs. This happens at timed intervals that are specified when registering a {{domxref('PeriodicSyncManager')}}.</dd>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +<h3>Requesting a periodic sync</h3>
Make sure headings are upper case.

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +<h1>Removing a periodic sync to stop syncing articles in the background</h1>
```suggestion
<h3>Removing a periodic sync to stop syncing articles in the background</h3>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +<h1>Removing a periodic sync to stop syncing articles in the background</h1>
My inclination would be use a more conventional title. Have you seen examples on MDN introduced with longer titles like this?

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_register_method.html
> +<p>Returns a {{jsxref("Promise")}} that resolves with <code>undefined</code></p>
I think you can do {{jsxref('undefined')}}.

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_register_method.html
> +  <dd>There is no active {{domxref('ServiceWorker')}} present</dd>
```suggestion
  <dd>There is no active {{domxref('ServiceWorker')}} present.</dd>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_register_method.html
> +  <dd>If permission for background periodic sync is not granted</dd>
```suggestion
  <dd>The permission for background periodic sync was not granted.</dd>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_register_method.html
> +  <dd>If permission for background periodic sync is not granted</dd>
"Express coordinate ideas in similar form." (Strunk and White, rule II-19.)

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_register_method.html
> +  <dd>If the active window is not the main window (not of "auxiliary" or "top-level" type)</dd>
```suggestion
  <dd>The active window is not the main window (not of "auxiliary" or "top-level" type).</dd>
```

2020-08-27 17:51 UTC, jpmedley commented on PeriodicSyncManager/PeriodicSyncManager_unregister_method.html
> +  <dd>The unique {{jsxref('String')}} descriptor for the specific background sync</dd>
```suggestion
  <dd>The unique {{jsxref('String')}} descriptor for the specific background sync.</dd>
```

2020-08-27 17:51 UTC, jpmedley commented on ServiceWorker/ServiceWorkerGlobalScope_onperiodicsync_property.html
> +<h2 id="See_also">See also</h2>
```suggestion
```

2020-08-27 17:51 UTC, jpmedley commented on ServiceWorker/ServiceWorkerGlobalScope_onperiodicsync_property.html
> + <li><a href="https://web.dev/periodic-background-sync/">An article on using Periodic Background Sync</a></li>
I'd use the actual title of the article. Do that throughout.

2020-08-27 17:51 UTC, jpmedley commented on ServiceWorker/ServiceWorkerGlobalScope_periodicsync_event.html
> +    <td><code><a href="/en-US/docs/Web/API/ServiceWorkerGlobalScope/onperiodicsync">onperiodicsync</a></code></td>
```suggestion
    <td>{{domxref('ServiceWorkerGlobalScope.onperiodicsync')}}</td>
```

2020-08-27 17:51 UTC, jpmedley commented on ServiceWorker/ServiceWorkerRegistration_periodicSync_property.html
> +<p>A PeriodicSyncManager {{jsxref('Object')}}</p>
```suggestion
<p>A PeriodicSyncManager {{jsxref('Object')}}.</p>
```

2020-09-03 16:53 UTC, Rumyra commented on PeriodicSyncEvent/PeriodicSyncEvent_landing_landing.html
> +<p class="summary">The <code>PeriodicSyncEvent</code> interface of the <a href="https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_APIs">Web Periodic Background
I didn't intend to push this page - it was just notes, I used the other landing page as the main page - apologies

2020-09-03 16:53 UTC, Rumyra commented on PeriodicSyncEvent/PeriodicSyncEvent_landing_landing.html
> +<p>In this section, describe the API's purpose and usage cases in a bit more detail — why was a need recognized for it? What problems does it solve? What concepts does it involve? How do you use it,
I didn't intend to push this page - it was just notes, I used the other landing page as the main page - apologies

2020-09-03 16:54 UTC, Rumyra commented on PeriodicSyncEvent/PeriodicSyncEvent_landing_landing.html
> +<div>{{draft}}{{DefaultAPISidebar("Periodic Background Sync")}}</div>
Your tool spits out landing pages for each interface - as I mentioned I didn't mean to push this, I used the other interfaces landing page template. I'm not concerned about the extra landing pages generated by interfaces, I usually just ignore them

2020-09-07 14:28 UTC, Rumyra commented on PeriodicSyncManager/PeriodicSyncManager_landing_landing.html
> +</div>
I asked Jake - I quote "It came down to, under what circumstance would the user be happy with this site running small amounts of JS in the background? And the answer was: if they've installed it"

I'm just considering a phrase for this as it's good reasoning and deserves a mention

2020-09-07 14:29 UTC, closed without merging